language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ree
notifications:
  email:
    recipients:
      - jacek.jakubik@netguru.pl
      - tomasz.pewinski@netguru.pl

