version: 2

.build_template: &build_definition
  steps:
    - checkout
    - restore_cache:
        key: gems-{{ checksum "Gemfile.lock" }}
    - run: bundle check || bundle install
    - save_cache:
        key: gems-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/app/vendor/bundle
    - run: bundle exec rake
  working_directory: ~/app
  environment:
    - LANG: C.UTF-8

jobs:
  build_ruby2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3
  build_ruby2_2:
    <<: *build_definition
    docker:
      - image: ruby:2.2

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build_ruby2_5
      - build_ruby2_4
      - build_ruby2_3
      - build_ruby2_2
